name: React App Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout Repository Code
       - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js (Recommended for caching etc.)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Change to match your project’s Node version

      # 3️⃣ Install Dependencies & Build React App
      - name: Install Dependencies
        run: npm ci

      - name: Build React App
        run: npm run build

      # 4️⃣ Archive Build Directory
      - name: Archive Production Build
        run: |
          zip -r react-build.zip dist  # Vite = dist; for CRA use 'build'

      # 5️⃣ Upload Build to VPS via SCP
      - name: Upload Build to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "react-build.zip"
          target: "~/react-build.zip"

      # 6️⃣ SSH into VPS → Extract & Reload NGINX
       - name: Deploy to Linux server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /var/www/ainet2-web-build/*
            unzip -o ~/react-build.zip -d /var/www/ainet2-web-build/
            rm ~/react-build.zip
            sudo systemctl reload nginx
            overwrite: true
            debug: true
