name: Build and Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build React App
        run: npm run build

      # Archive Build Directory
      - name: Archive Production Build
        run: |
          zip -r build.zip dist  # Vite = dist; for CRA use 'build'

      - name: Deploy to Linux server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/**"
          target: "/var/www/ainet2-web-build/"
          strip_components: 0
          overwrite: true
          debug: true
